### ISSUE TITLE
How to do Postgres PGP Public Key Decryption on the App Server

### ISSUE THREAD

**Issue by tamiswa** [jmazzi/crypt_keeper#100]
I am trying to use the PostgreSQL PGP Public Key encryptor.  However, mention somewhere in the docs that:
> The private key is optional. If the private key is not present the ciphertext value is returned instead of the plaintext

and...

 > Encryption is possible with only a public key. Any server that needs access to the plaintext will need the private key.

Do you have any idea how I would do decryption (example code etc.) on the app server so I can keep the private keys completely off my database server?

Thanks for the awesome library!

**Comment by jmazzi** [comment]
@tamiswa it's pretty much the same as the others. The main difference is that there are two new options for thez `crypt_keeper` class method you use in your model.

```ruby
crypt_keeper public_key: 'path/to/public.asc`, private_key: 'path/to/private.key`, key: 'passphrase'
```

Just omit the private key where it is not needed.

**Comment by tamiswa** [comment]
@jmazzi I don't think I explained my question clearly enough.  I know that all I have to do to bypass decryption from within Postgres is not provide the private key to the crypt_keeper method.  My question is once I have the cyphertext, do you know how I can decrypt myself in the model?  I have tried using libraries like https://github.com/ueno/ruby-gpgme with no success.

**Comment by jmazzi** [comment]
Can you give a code example from your model showing the expected behavior
you want?
