### ISSUE TITLE
Become really transparent for ActiveRecord

### ISSUE THREAD

**Issue by Kukunin** [jmazzi/crypt_keeper#102]
Meantime while this gem is really cool, it's not fully transparent for models. I can mention at least two things it affects:
1. If I want to crypt not-string attribute (integer or date), I'm forced to change db column type to :text, and Rails casting stop to work for me. I need to implement own workarounds (btw, do you know pretty solutions)?
2. New Rails 4.2 behaviour with form helpers, related to https://github.com/jmazzi/crypt_keeper/issues/99. They use `attribute_before_type_cast` method. So, if I have date encrypted field, and I've figured out typecasting from string to DateTime object, I can't get string value for date. `attribute` will return DateTime, while `attribute_before_type_cast` will return encrypted value for me. 

So, I need, the best way is to encrypt/decrypt somewhere before `attribute_before_type_cast` method + provide cool solution for rails casting to integer, date or datetime types. This way the gem will be really transparent, and even more rocks!

Thank you!

**Comment by jmazzi** [comment]
1) How would you store encrypted text in a date field? Likewise, how would you store encrypted text in a integer type field?

2) That isn't something I currently have time to work on, sorry.

**Comment by Kukunin** [comment]
Thanks for quick response.

1) Converting db column to text is ok. I'm asking about a clean solution to keep rails autocasting for this field. I wonder if there is already clean solution, not workarounds. If yes, you can just reflect that solution in README etc.

2) No problem. I just want to discuss and figure out the best solution. Tell me you vision, and maybe I'll find time to make the PR for this.

**Comment by Kukunin** [comment]
I'm not familiar with type casting system in the rails, but I believe you are, and you can point me the way to make this improvement, if you think it's reasonable
