### ISSUE TITLE
crypt keeper gem touching Rails model when nothing updates, causing updated_at to refresh

### ISSUE THREAD

**Issue by matisoffn** [jmazzi/crypt_keeper#106]
I have the snippet below in my `User` model:

```ruby
crypt_keeper :secret_field, encryptor: :aes_new, key: ENV['SECRET_KEY_BASE'], salt: 'secret salt'
```

It's encrypting the data using the specified encryptor just fine, however, when calling the `save` method on the model it resets the `:secret_field` on the model causing the `updated_at` to also be reset.

For example, on another model, the snippet below would do nothing:

```ruby
client = Client.find(1)
client.save
```

However, on a model with crypt keeper it updates the encrypted field and then sets the updated_at.  How can this be prevented?

**Comment by matisoffn** [comment]
Anything?

**Comment by jmazzi** [comment]
@matisoffn crypt_keeper uses a rails serializer behind the scenes. There is a known problem with rails serializers that causes all records to be considered `dirty?` on save. See rails/rails#8328
