### ISSUE TITLE
Rails 5.0 beta: Bundler could not find compatible versions for gem "activerecord"

### ISSUE THREAD

**Issue by mikecarroll** [jmazzi/crypt_keeper#107]
Playing around with the beta of Rails 5.0, and hit this gem compatibility issue:

```
Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    crypt_keeper (~> 0.20) was resolved to 0.20.0, which depends on
      activerecord (< 4.3, >= 3.1)

    rails (~> 5.0.0.beta1) was resolved to 5.0.0.beta1, which depends on
      activerecord (= 5.0.0.beta1)
```

Happy to investigate how the compatibility of the gem with Rails 5.0 and submit a PR updating the dependencies, if nobody else is working on it already.

**Comment by jmazzi** [comment]
Hi @mikecarroll, thanks for the report. I have not used tested this with rails 5.0. Please feel free to upgrade the gemspec and report your findings, it would be greatly appreciated!

**Comment by jesperronn** [comment]
@mikecarroll Any updates you can share? I ran into this right now.

**Comment by jesperronn** [comment]
I made this change in a fork: https://github.com/jesperronn/crypt_keeper/pull/1

**Comment by itspriddle** [comment]
Rails 5 support was added in #125 and is available on master. A new release will be published soon.

**Comment by jesperronn** [comment]
hey @jmazzi could you please provide a new release, so that I can use a released version in my Rails 5 app?

This issue has gotten old, but most recent release (0.22.0 as of writing) is still missing the changes required for Rails 5
