### ISSUE TITLE
Is salt meant to be used at row or at model level?

### ISSUE THREAD

**Issue by robotex82** [jmazzi/crypt_keeper#131]
Perhaps I'm getting it totally wrong, but is it possible to store the salt as column in the database on a per row level?

I think about other enryption solutions, that store one salt per encrypted record

Just to clarify, why is salt the same for all record of a model?

Thanks in advance!

Best Regards,
Roberto

**Comment by jmazzi** [comment]
@robotex82 it's not something that crypt_keeper provides, but you could make your own encryptor that works similar to the included which implements fetching it's salt from a column.
