### ISSUE TITLE
Can i disable crypt_keeper in some environment

### ISSUE THREAD

**Issue by zupaazhai** [jmazzi/crypt_keeper#136]
in dev environment, i would like to disable crypt_keeper. have any config or can i do this feature?

**Comment by itspriddle** [comment]
We have a feature intended for tests that you could use to accomplish this. In an initializer like `config/initializers/crypt_keeper.rb`, you can set the following:

```
if Rails.env.development?
  CryptKeeper.stub_encryption = true
end
```

**Comment by zupaazhai** [comment]
i found this error when start rails server 
`undefined method `stub_encryption=' for CryptKeeper:Module (NoMethodError)`

**Comment by itspriddle** [comment]
Can you confirm the version of CryptKeeper you're using? It was added in v0.21.0 https://github.com/jmazzi/crypt_keeper/blob/v0.21.0/lib/crypt_keeper.rb#L15

**Comment by zupaazhai** [comment]
Aha ok I used lower version

`gem 'crypt_keeper', '~> 0.20.0'` 

thanks for your support.
