### ISSUE TITLE
Ruby 2.4 - can't modify frozen String

### ISSUE THREAD

**Issue by michaelrigart** [jmazzi/crypt_keeper#147]
Ruby: 2.4
Rails: 5.1.4
Testframework: Minitest
Crypt_keeper: 1.1.1

I'm running into some issues using the above configuration. The error occurs when running the following ActiveSupport::TestCase setup, but not during application usage.

```ruby
 # frozen_string_literal: true

class Revenue < ApplicationRecord
  crypt_keeper :field_1, :field_2,
               encryptor: :aes_new,
               key: ENV['CRYPT_KEEPER_KEY'],
               salt: ENV['CRYPT_KEEPER_SALT'],
               encoding: 'UTF-8'
end
```

```ruby
# frozen_string_literal: true

require 'test_helper'

class DestroyServiceTest < ActiveSupport::TestCase
  setup do
    params = {
      field_1: 'Value 1',
      field_2: 'Value 2'
    }

    @object = Model.create(params)
  end

  test 'some test' do
    # perform some test
  end
end
```

The error (```RuntimeError: can't modify frozen String```) gets triggered on ```@object = Model.create(params)``` . 

I was able to track it down to the ``` force_encodings_on_fields``` method inside ```lib/crypt_keeper/model.rb ``` . 

When I change 

```ruby
send(field).force_encoding(crypt_keeper_encoding)
```

To 

```ruby
send(field).dup.force_encoding(crypt_keeper_encoding)
``` 

The error no longer gets triggered, but only when you disable spring as well.

**Comment by michaelrigart** [comment]
Another observation is that these errors only pop up when using binary als column type. 
When changing the column types to "text", we're all in the green again. 

Currently using Postgres 10.

**Comment by jmazzi** [comment]
@michaelrigart Could you provide the backtrace?

**Comment by michaelrigart** [comment]
@jmazzi : Sorry for the late reply. I'll reply one later today.
