### ISSUE TITLE
Gave me this error on Rails 5.

### ISSUE THREAD

**Issue by zoopyserg** [jmazzi/crypt_keeper#152]
````
NameError: uninitialized constant CryptKeeper::Provider::ActiveSupport
````

**Comment by itspriddle** [comment]
Hi @zoopyserg – can you tell us the specific version of Rails and CryptKeeper you are using? I'm not able to reproduce this with Rails 5.1.4 + CryptKeeper 2.0.0.rc1

`CryptKeeper::Provider::ActiveSupport` was introduced in the latest CryptKeeper, 2.0.0.rc1.

**Comment by itspriddle** [comment]
Closing this as we've not heard back. Please feel free to reopen with the info requested above if you are still having trouble. Thanks!

**Comment by reggieb** [comment]
I had the same error running Rails 5.1.5 and can confirm that using CryptKeeper 2.0.0.rc1 fixed the issue.
