### ISSUE TITLE
Guidance on using ActiveRecord batches with search_by_plaintext?

### ISSUE THREAD

**Issue by melissawahnish** [jmazzi/crypt_keeper#157]
Would you be able to provide some more guidance for using ActiveRecord batches with search_by_plaintext as you recommend in the Readme?  

I am encrypting email addresses but also need to look up the user by email in order to login in the user.  The production database has about 15,000 records, and a test deploy caused a pretty dramatic drain on the memory.

I have tried implementing the methods in the Rails docs for [ActiveRecord Batches](http://api.rubyonrails.org/classes/ActiveRecord/Batches.html) without success.

Thanks!

**Comment by itspriddle** [comment]
If it fits in with your business rules, I'd actually _strongly_ recommend not encrypting your email field at all. As a rule of thumb in our apps we avoid using CryptKeeper on anything that will need to be queried directly via the DB. It is technically possible to do, but as you can see below you really have to go against the grain with ActiveRecord to do it in a way that performs quickly.

That said, if this is something you absolutely need to do in your app, the best way would be to store a separate hash of the email in your User model. It would need to be unique across all users to ensure lookups by the hash return the correct user. That field can then be indexed by your DB to perform quicker lookups. Something like this ought to work:

```ruby
class User < ApplicationRecord
  # Create a secure salt and keep it in your .env or similar
  # SecureRandom.hex(64) will give you a safe hash
  EMAIL_HASH_SALT = ENV["USER_EMAIL_HASH_SALT"]

  before_save :set_email_hash

  validates :email_hash, presence: true, uniqueness: true

  def self.generate_email_hash(email)
    Digest::SHA256.hexdigest("#{email}-#{EMAIL_HASH_SALT}")
  end

  def self.find_by_email(email)
    where(email_hash: generate_email_hash(email)).first!
  end

  private

  def set_email_hash
    self.email_hash = self.class.generate_email_hash(email)
  end
end
```

A migration might look like:

```ruby
class AddEmailHashToUsers < ActiveRecord::Migration[5.1]
  def change
    add_column :users, :email_hash, :string
    add_index :users, :email_hash, unique: true
  end
end
```

To populate the DB initially you would need to iterate through each User to trigger the callback to store the hash. This is going to somewhat slow unfortunately:

```ruby
User.find_each { |user| user.save! }
```

**Comment by melissawahnish** [comment]
Thanks so much!
