### ISSUE TITLE
Cipher selection issue with ActiveSupport::MessageEncryptor

### ISSUE THREAD

**Issue by adampope** [jmazzi/crypt_keeper#160]
I'm upgrading from Rails 5.1 to 5.2 and have had to switch from AES to the ActiveSupport::MessageEncryptor.

I performed the `decrypt_table!` -> `encrypt_table!` process in my dev environment and everything seemed ok, encrypted data was written back into the database.  However, I was getting `ActiveSupport::MessageEncryptor::InvalidMessage` errors when trying to load records.  I think this was my problem, and some permutation of restarting puma or spring resolved that.

However, my investigation into what could be wrong led me to discover a possible inconsistency that might be a problem in the future.  Whilst trying to decrypt the encrypted data by following the crypt_keeper and active support code line-by-line, I found that the data crypt_keeper had persisted did not have an `auth_tag`, but active support was trying decrypt the data believing there should be an `auth_tag`.

In my instance of `ActiveSupport::MessageEncryptor` I had created on the console, the selected cipher was `aes-256-gcm` because `use_authenticated_message_encryption` was true.  Through instrumenting the crypt_keeper gem I found that at the time it creates its instance of MessageEncryptor `use_authenticated_message_encryption` is false, leading it to use the `aes-256-cbc` cipher.

It is concerning to me that the value of the `use_authenticated_message_encryption` setting is changed during the application's initialization (I haven't found where or why yet) and that this determines the cipher for crypt_keeper.  If that load order were to change then it is possible crypt_keeper could have an instance of ActiveSupport::MessageEncryptor using a difference cipher, leading to unreadable data.

I'm not a cryptography expert and don't know whether `cbc` or `gcm` is more appropriate, but I think crypt_keeper should pass the `cipher` option to the ActiveSupport::MessageEncryptor initializer and make an explicit selection that cannot be changed inadvertently by externalities.

**Comment by jmazzi** [comment]
This is a late response, but crypt_keeper doesn't use `
ActiveSupport::MessageEncryptor` directly. What does your model look like?
