### ISSUE TITLE
Migration to 2.0

### ISSUE THREAD

**Issue by vnazarenko** [jmazzi/crypt_keeper#162]
Hello, is there any other, more gracefull possibility of migration, except stop/start world. Our system is pretty large, so it's kinda difficult thing to do that

**Comment by andrewostroumov** [comment]
We discussed with @vnazarenko and concluded to prepend provider name to encrypted password. So we will have a field in the db without provider `nhOG5AqEEGOlJvFmgFYv+g==\n` - default mysql_aes_new and with provider `active_support:WEhSRFlzV041TlV...`. We will migrate whole system to new format and can process multiple providers.

**Comment by andrewostroumov** [comment]
I surprised that every time I update user password was updated to. This makes this gem useless in production because ActiveSupport::KeyGenerator#generate_key take 100ms every time is user update. Please consider switch from serializers to native setters.
