### ISSUE TITLE
Failure to support encryption for :string column type

### ISSUE THREAD

**Issue by jesperronn** [jmazzi/crypt_keeper#168]
https://github.com/jmazzi/crypt_keeper/blob/4bfa80d08a6b9c473be923a44853e7570c5aa482/lib/crypt_keeper/model.rb#L13

This line ensures that `:string` column type will not work with crypt_keeper.

Is there a specific reason to do so?

I made an experiment locally on my machine, and `:string` actually works for me (Sqlite and Postgres).
What am I overlooking? Or, can we add the column type :string here?

Details in https://github.com/jmazzi/crypt_keeper/blob/4bfa80d08a6b9c473be923a44853e7570c5aa482/lib/crypt_keeper/model.rb#L13:

To use in your Rails app, add this to `config/initialzers/crypt_keeper.rb`:
```
module CryptKeeper
  module Model

    # overrides column types in https://github.com/jmazzi/crypt_keeper/blob/master/lib/crypt_keeper/model.rb
    def ensure_valid_field!(field)
      ar_column = self.class.columns_hash["#{field}"]
      column_type = ar_column.type
      if ar_column.nil?
        raise ArgumentError, "Column :#{field} does not exist"
      elsif !%i(text binary string).include?(column_type)
        raise ArgumentError, "Column :#{field} (#{column_type}) must be of type 'text' or 'binary' \
to be used for encryption"
      end
    end
  end
end
```

**Comment by jmazzi** [comment]
@jesperronn this is to avoid the truncating of cipher_text.

**Comment by jesperronn** [comment]
Okay, so if I understand you correctly: 

Always avoid encryption of column `type :text`, since there is a risc the encrypted value is truncated, and thus will destruct data.

Thanks for clarifying 👍

**Comment by jmazzi** [comment]
@jesperronn correct! It avoids silent failures making decryption impossible.
