### ISSUE TITLE
jamming config.active_record.verbose_query_logs = true

### ISSUE THREAD

**Issue by masterkain** [jmazzi/crypt_keeper#169]
hello,
when enabling Rails' `config.active_record.verbose_query_logs = true` all one can see in logs is

```
  UserAuthToken Destroy (0.4ms)  DELETE FROM "user_auth_tokens" WHERE "user_auth_tokens"."account_id" = $1  [["account_id", 14665]]
  ↳ /Users/kain/.rvm/gems/ruby-2.5.3/bundler/gems/crypt_keeper-4bfa80d08a6b/lib/crypt_keeper/log_subscriber/postgres_pgp.rb:17
```

for every query.

any way to not pollute this option?

**Comment by jmazzi** [comment]
crypt_keeper uses ActiveRecord's log subscriber support. Verbose logs include everything related to logging; you can't suppress it without patching crypt_keeper.
