### ISSUE TITLE
How to use WHERE LIKE queries on encrypted fields?

### ISSUE THREAD

**Issue by Ghost---Shadow** [jmazzi/crypt_keeper#173]
I want to use a query like `where('email LIKE %github%')` but since the emails column is encrypted, I cannot use this technique.

The `Model.decrypt_table!` is an inplace solution. Is there an online way of decrypting the rows?

**Comment by jmazzi** [comment]
@Ghost---Shadow Unfortunately you can't search with LIKE through crypt_keeper. You can use the search methods listed here https://github.com/jmazzi/crypt_keeper#searching
