### ISSUE TITLE
ActiveSupport::MessageEncryptor::InvalidMessage after upgrading from Rails 5.2.6 to 6.0.4

### ISSUE THREAD

**Issue by danielyazbek** [jmazzi/crypt_keeper#190]
HI there,

I'm using crypt_keeper v2.2.0
After upgrading from Rails 5.2.5 to 6.0.4 I can no longer decrypt data that was encrypted by crypt_keeper before the rails upgrade.

Using active_support encryption, keys and salt have not changed.

When trying to get an encrypted value, i get the error:

`ActiveSupport::MessageEncryptor::InvalidMessage`

**Comment by danielyazbek** [comment]
SOLVED:
`Rails.config.active_support.use_authenticated_message_encryption = false`
See https://www.bigbinary.com/blog/rails-5-2-uses-aes-256-gcm-authenticated-encryption-as-default-cipher-for-encrypting-messages

**Comment by akapitula** [comment]
Rails.config.active_support.use_authenticated_message_encryption = false
Also worked for me, the problem was related with the dynamic vector used to encrypt the messages. (use_authenticated_message_encryption changes the encryption algorithm)
