### ISSUE TITLE
Devise & Crypt-Keeper for same model

### ISSUE THREAD

**Issue by samuelwaeny** [jmazzi/crypt_keeper#191]
Hi, we have just spent a night of debugging trying to find the cause for a very odd bug; 
we were not able to find out the root cause yet, maybe somebody can relate and / or has an idea how this can happen:

- We have a model where some of the fields are encrypted using crypt_keeper (with the active_session encryptor).
- We added devise for authenticating the same model (not using the same fields)

When we deployed this change to production, we started seeing `ActiveSupport::MessageEncryptor::InvalidMessage` errors: - Only for records that were existing, Newly created records worked fine.
- When removing devise from the model everything worked again. 
- The key and the salt did not change of course.
- When creating an instance of the encryptor in the console, the old values (directly copied from the database) were decrypted without any problems.
- In testing the problem never happend because there are no persisted, encrypted objects / fields.
- The rails version (and also no other gems) changed version, also no updates on the server
- The encrypted ciphertexts after adding devise were all much longer than the ones of the version without devise added to the model.

Could it be that devise somehow changes the included classes that get used by crypt_keeper?

Thank you in advance, 
Sam

**Comment by jmazzi** [comment]
What are the field names on the model you’re encrypting and which ones are you using with devise? Are you able to reproduce this with a dummy rails app using devise and crypt keeper with the same fields to see if can be reproduced?

**Comment by samuelwaeny** [comment]
Devise: `:token`, `:password`
crypt keeper: `crypt_keeper :last_name, :kk_field2, :street, :birthdate,
               encryptor: :active_support, key: ENV.fetch('KEY'), salt: ENV.fetch('SALT')`

As soon as I will find some free minutes I'll try to reproduce it in a empty dummy project and get back in touch with you.
