### ISSUE TITLE
Incorrect rails 7 dependency specified in Gemspec

### ISSUE THREAD

**Issue by dannyy83** [jmazzi/crypt_keeper#197]
Installing crypt_keeper gem from rubygems (via bundler) is incompatible with rails 7.0.x.y

Steps to reproduce:

```
gem 'rails', '~> 7.0'
gem 'crypt_keeper'
```

```
$ bundle install
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies....
Bundler could not find compatible versions for gem "activerecord":
  In snapshot (Gemfile.lock):
    activerecord (= 7.0.2.3)

  In Gemfile:
    crypt_keeper was resolved to 2.3.0, which depends on
      activerecord (>= 4.2, <= 7)
```

It looks like the version uploaded to rubygems incorrectly specifies the minimum version for activerecord (it should be `< 7.1`)

As a workaround, the gemsepc in github does not have this problem, so

```
gem 'crypt_keeper', github: 'jmazzi/crypt_keeper'
```

**Comment by tkling** [comment]
@jmazzi Can you please cut a new gem version with the code currently in the master branch? Rails 7.0.1+ apps can't use this gem from rubygems right now due to the dependency version constraint issue mentioned in this ticket.

**Comment by akshay-birajdar** [comment]
Friendly ping for cutting a new release.

**Comment by kayodeadeniyi** [comment]
@jmazzi Thanks for your work. This is another friendly ping for cutting a new release.

**Comment by jmazzi** [comment]
Please submit a pull request and I will cut a new gem for you. Thanks!

**Comment by kayodeadeniyi** [comment]
@jmazzi The fix is already merged to master, you just need to release the tag for the last merge to master so as to make it available from rubygems. Thank you
