### ISSUE TITLE
crypt_keeper re-encrypts attributes on every save

### ISSUE THREAD

**Issue by zelaznik** [jmazzi/crypt_keeper#198]
It looks like this issue was raised back in 2013:

https://github.com/jmazzi/crypt_keeper/issues/61

However the hope was that a future edition of Rails could solve the problem.  This has not been the case.  I'm wondering if there are any decent work-arounds.  We've noticed some performance issues.  We also keep a version history of changed values in the database, so these encrypted values get stored every time something is saved to the database, even if the plain-text values are the same.

I know that not a lot of people maintain this gem, so if you know the general direction for how this can be fixed, let me know, and I could possibly submit a PR.

**Comment by jmazzi** [comment]
I unfortunately do not have much guidance to offer on this. I would suggest reviewing active_record intervals to see if there are any options.
