### ISSUE TITLE
Cannot have multiple encryptors on one model

### ISSUE THREAD

**Issue by ghost** [jmazzi/crypt_keeper#199]
I am trying to add two different encryptors on a model and seems to only use the last one I specify. For example:
```
class MyModel < ActiveRecord::Base
  crypt_keeper :attrib_1, encryptor: :aes_gcm_json
  crypt_keeper :attrib_2, encryptor: :aes_gcm_yaml
```
The model ends up only using `aes_gcm_yaml` for all the fields, is there a way to do this?

**Comment by jmazzi** [comment]
This is not something that we've added explicit support to do. I would recommend using separate tables.

**Comment by ghost** [comment]
Am using `v0.22.0` and from what I can see in https://github.com/jmazzi/crypt_keeper/blob/v0.22.0/lib/crypt_keeper/model.rb

The problem is because the options (specifically `crypt_keeper_encryptor`) are stored as `class_attribute`s.

It could have been passed as arguments to private functions but from what I can see the main usage is for `encrypt!` and `decrypt!`?

Moving a column to a separate table will be a lot more work so not an option.

If this is a limitation I think it is important to mention this in the Readme.
