### ISSUE TITLE
Allow rails 7.0.X

### ISSUE THREAD

**Issue by santir489** [jmazzi/crypt_keeper#201]
@jmazzi
master already support rails 7.0.x , can you cut a release with it ?
It seems many folks have requested it https://github.com/jmazzi/crypt_keeper/issues/197

**Comment by Capncavedan** [comment]
Would love to see https://github.com/jmazzi/crypt_keeper/pull/200 merged and new gem cut

**Comment by jmazzi** [comment]
Thanks for bumping this. The tests were failing the last time I checked, and I asked for them to be corrected. I'm re-running the tests, and if they look good, I will cut a gem.

**Comment by jmazzi** [comment]
Closing this in favor of #200
