### ISSUE TITLE
Guidelines for key and salt

### ISSUE THREAD

**Issue by creativetags** [jmazzi/crypt_keeper#78]
I would love to see an example of how to implement the key and salt securely.

How long do they need to be? Should they be the same for each column or generate a random one each time?

**Comment by swaps19** [comment]
@jmazzi It would be great if you place this information in the `readme` file itself. As many new users might face this situation.

**Comment by itspriddle** [comment]
@swaps19 thanks for the suggestion! I've opened https://github.com/jmazzi/crypt_keeper/pull/153 to get this added, likely to land in master next week.
