### ISSUE TITLE
AESNew ecryption: support Postgres Text[] types

### ISSUE THREAD

**Issue by Fritzinger** [jmazzi/crypt_keeper#96]
Given an activerecord table with a text column created with array: true

    t.text     "my_column",       default: [], array: true

And 

    class MyModel < ActiveRecord::Base
      crypt_keeper :my_column, encryptor: :aes_new, key: 'CRYPT_KEEPER_KEY', salt: 'CRYPT_KEEPER_SALT'
     end

`MyModel.encrypt_table!` fails:

    TypeError: no implicit conversion of Array into String
        from /Users/fritz/devprojects/smartpropertysystems/.gems/gems/aes-0.5.0/lib/aes/aes.rb:119:in `update'
        from /Users/fritz/devprojects/smartpropertysystems/.gems/gems/aes-0.5.0/lib/aes/aes.rb:119:in `_encrypt'
        from /Users/fritz/devprojects/smartpropertysystems/.gems/gems/aes-0.5.0/lib/aes/aes.rb:58:in `encrypt'
        from /Users/fritz/devprojects/smartpropertysystems/.gems/gems/aes-0.5.0/lib/aes/aes.rb:5:in `encrypt'

It would be good if CryptKeeper could encrypt each value in the text[] column.

**Comment by jmazzi** [comment]
@Fritzinger sorry for the last response. This isn't a bad idea but it's not something I would personally use. If you're willing to implement it, and the implementation is clean, I would consider merging it.
