### ISSUE TITLE
Performance....

### ISSUE THREAD

**Issue by mhenrixon** [jmazzi/crypt_keeper#98]
So I couldn't use your upgrade scripts because of whatever the reason was so needed to write my own upgrade scripts. Problem is it is taking hours for a mere 10 000 attribute values. How can I speed it up?

**Comment by jmazzi** [comment]
Which type of encryption are you using?

On Tue, Mar 24, 2015 at 6:14 AM, Mikael Henriksson <notifications@github.com

**Comment by mhenrixon** [comment]
New AES

**Comment by jmazzi** [comment]
The only thing I could suggest is using something like sidekiq/celluloid to
spread the work out over a few workers to complete it faster.

**Comment by mhenrixon** [comment]
I just discovered how retarded this is... You are using Armor and armor takes ENVIRONMENT variables!!!! no other way to override it! https://github.com/cyx/armor/blob/master/lib/armor.rb#L19 solution is to set the environment variable in a class of my own before I initialize the provider.

```ruby
# encoding: utf-8
require 'crypt_keeper/provider/aes_new'

module CryptKeeper
  module Provider
    class BaseAesNewEncryptor < CryptKeeper::Provider::AesNew
      def initialize(options = {})
        ENV['ARMOR_HASH'] = 'sha512'
        ENV['ARMOR_ITER'] = '10'
        super
      end

      def encrypt(value)
        super(value)
      end

      def decrypt(value)
        super(value).to_s.force_encoding('utf-8')
      end
    end
  end
end
```

We shouldn't force people to use something like this that can't easily be overridden or customized. We don't need uber security for the email addresses and I must say I was disappointed to discover that sha512 with 5000 iterations is the only possible way except through an environment variable. Did you ever try to upgrade a big table to this? I mean for signups and regular updates its ok I suppose but even at 1000 iterations it didn't finish 10 000 records in under an hour.

**Comment by jmazzi** [comment]
Digest has nothing to do with the encryption iterations, that is solely for digesting the passphrase you use in your model, aka, the secret key. It is called once per-model the first time ruby requires the file, it has nothing to do with the performance of the encryption.

If you are not happy with the service provided here, feel free to submit a request for a full refund.

**Comment by mhenrixon** [comment]
Aha so maybe it would be enough to reuse an instance of the provider then? I don't think I memoized it in the migration. That should solve it for me!!

**Comment by mhenrixon** [comment]
Yup! All I had to do was memoize the created provider :dancers:
